# Generated by Django 3.1.7 on 2021-02-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Logintable',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
